#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #
#  @Bitcoinera -> @bitcoinera:matrix.org       #                              
#                                              #
################################################
# Comando:
# $CLI query account <wallet> --trust-node=true
#
CLI=kvcli

$CLI keys list

echo  "¿Qué wallet quieres usar?"
read -r wallet

$CLI query account ${wallet} --trust-node=true
