#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #
#  @Bitcoinera -> @bitcoinera:matrix.org       # 
#                                              #
################################################
# Comando:
# $CLI keys add <nombreWallet>
#
CLI=kvcli

echo "¿Qué nombre quieres ponerle a la wallet?"
read -r name

$CLI keys add ${name}