#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #
#  @Bitcoinera -> @bitcoinera:matrix.org       # 
#                                              #
################################################
# Comando:
# $CLI tx staking delegate <validatorAddress> <amountToBond> --from <delegatorKeyName> --gas auto --gas-prices <gasPrice> --fees 1000photino
#
##Variables:
#
PROJECT=kava
DAEMON=kvd
CLI=kvcli
UNIT=ukva

chain_id=$(curl -s http://localhost:26657/status | jq -r '.result.node_info.network')

$CLI keys list

echo "¿Qué wallet quieres usar?(${PROJECT}123...)"
read -r wallet

echo "¿Qué cantidad quieres delegar?"
read -r amount

echo "¿A qué validador has elegido?(${PROJECT}valoper...)"
read -r delegator

$CLI tx staking delegate ${delegator} ${amount}$UNIT --from=${wallet} --chain-id=${chain_id} --fees=5000${UNIT} -y
