#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #
#                                              #
################################################
# Comando:
# $CLI keys add --recover <nombreWallet>
#
CLI=kvcli

echo "¿Qué nombre quieres ponerle a la wallet?"
read -r name

$CLI keys add --recover $name