#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #
#  @Bitcoinera -> @bitcoinera:matrix.org       # 
#                                              #
################################################
# Script para redelegar fondos
#
# Comando:
# $CLI tx staking redelegate \
#   --addr-validator-source=<account_$PROJECTval> \
#   --addr-validator-dest=<account_$PROJECTval> \
#   --shares-fraction=50 \
#   --from=<key_name> \
#   --chain-id=<chain_id>
#
# Variables:
#
PROJECT=kava
DAEMON=kvd
CLI=kvcli
UNIT=ukva

chain_id=$(curl -s http://localhost:26657/status | jq -r '.result.node_info.network')

$CLI keys list

echo "¿Qué wallet quieres usar?(${PROJECT}123...)"
read -r wallet

echo "¿De qué validador quieres desvincularte?(${PROJECT}valoper...)"
read -r oldvalid

echo "¿A qué validador quieres vincularte?(${PROJECT}valoper...)"
read -r newvalid

echo "¿Qué cantidad quieres vincular?"
read -r amount

$CLI tx staking redelegate ${oldvalid} ${newvalid} ${amount} --from=${wallet} --chain-id=${chain_id} --fees=5000${UNIT} -y
