#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #
#  @Bitcoinera -> @bitcoinera:matrix.org       # 
#                                              #
################################################
# Script para realizar una transacción
#
# $CLI tx send <destination_$PROJECT> 10faucetToken \
# --chain-id=<chain_id> \
# --from=<key_name> \
#
# Variables:
DAEMON=kvd
CLI=kvcli
UNIT=ukva

chain_id=$(curl -s http://localhost:26657/status | jq -r '.result.node_info.network')

$CLI keys list

echo  "¿Qué wallet quieres usar?(puedes usar su nombre)"
read -r wallet

echo "¿A qué wallet quieres enviar?"
read -r destiny

echo "¿Qué cantidad?"
read -r amount

$CLI tx send ${destiny} ${amount}$UNIT --chain-id=${chain_id} --from=${wallet} --fees=5000${UNIT} -y
