#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #
#                                              #
################################################
# Script para hacer unbond
#
# Comando:
# $CLI tx staking unbond \
#   --validator=<account_$PROJECTval> \
#   --shares-amount=12.1 \
#   --from=<key_name> \
#   --chain-id=<chain_id>
# Variables:
PROJECT=kava
DAEMON=kvd
CLI=kvcli
UNIT=ukva

chain_id=$(curl -s http://localhost:26657/status | jq -r '.result.node_info.network')

$CLI keys list

echo "¿Qué wallet quieres usar?(${PROJECT}123...)"
read -r wallet

echo "¿De que validador quieres desvincularte?(${PROJECT}valoper...)"
read -r validator

echo "¿Qué cantidad de ${UNIT} quieres desvincular?"
read -r amount

$CLI tx staking unbond ${validator} ${amount} --from=${wallet} --chain-id=${chain_id} --fees=5000${UNIT} -y