#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #
#  @Bitcoinera -> @bitcoinera:matrix.org       # 
#                                              #
################################################
# Script para ver los validadores
#
# Comando:
# $CLI query tendermint-validator-set --trust-node=true
#
CLI=kvcli

$CLI query tendermint-validator-set --trust-node=true