#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl) -> @cosmaut:matrix.org      #
#  @DerFredy       -> @derfredy:matrix.org     #                              
#                                              #
################################################
CLI=kvcli

account=`$CLI keys list | awk 'FNR==2{print $3}'`

echo "account = $account"

