#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################
# Shows balance
DAEMON=kvd
CLI=kvcli
UNIT=ukva

chain_id=`curl -s http://localhost:26657/status | jq -r '.result.node_info.network'`

account=`${CLI} keys list | awk 'FNR==2{print $3}'`

$CLI query account $account --chain-id=$chain_id --trust-node=true --output=json | jq

