#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl) -> @cosmaut:matrix.org      #
#  @DerFredy       -> @derfredy:matrix.org     #
#  @Bitcoinera -> @bitcoinera:matrix.org       #                               
#                                              #
################################################
# Runs $DAEMON in a tmux terminal. Use it as cronjob to keep $DAEMON alive
#
DAEMON=kvd

if pgrep -x "$DAEMON" > /dev/null
then
    echo "$DAEMON is Running"
else
    echo "Restarting $DAEMON"
    tmux kill-server
    tmux new-session -s "$DAEMON" -d -n "main"
#    tmux send-keys -t "$DAEMON:main" C-z '~/bin/$DAEMON start --minimum_fees=1STAKE,1photino' Enter
#    tmux send-keys -t "$DAEMON:main" C-z '~/bin/$DAEMON start --minimum-gas-prices=0.01photinos,0.0001stake' Enter
    tmux send-keys -t "$DAEMON:main" C-z '~/bin/$DAEMON start' Enter
    tmux split-window -v
    tmux select-pane -t 1
    tmux send-keys "~/scripts/block" C-m
    echo "$(date +"%Y-%m-%d %T") $DAEMON Restarted" >> ~/$DAEMON.log
fi

