#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl) -> @cosmaut:matrix.org      #
#  @DerFredy       -> @derfredy:matrix.org     #
#  @Bitcoinera -> @bitcoinera:matrix.org       #                               
#                                              #
################################################
#
# go version go1.11.5 linux/amd64
#
PROJECT=kava
DAEMON=kvd

mkdir -p $GOPATH/src/github.com/$PROJECT
cd $GOPATH/src/github.com/$PROJECT
git clone https://github.com/$PROJECT/$PROJECT-sdk
git fetch --tags
cd $PROJECT-sdk && git checkout master
make tools install
clear
echo ""
$DAEMON version --long
$CLI version --long
