#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################
# Shows cosmovaloper
PROJECT=kava
DAEMON=kvd
CLI=kvcli
UNIT=ukva

keyname=`$CLI keys list | awk 'FNR==2{print $1}'`
cosmovaloper=`$CLI keys show ${keyname} --bech=val | awk 'FNR==2{print $3}'`

echo "cosmovaloper = $cosmovaloper"

