#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl) -> @cosmaut:matrix.org      #
#  @DerFredy       -> @derfredy:matrix.org     #                              
#                                              #
################################################
PROJECT=kava
DAEMON=kvd
CLI=kvcli
UNIT=ukva

keyname=`$CLI keys list | awk 'FNR==2{print $1}'`
chain_id=`curl -s http://localhost:26657/status | jq -r '.result.node_info.network'`
pubkey=`$DAEMON tendermint show-validator`

echo "Recuerda que este script usa $UNIT como moneda, si no es asi debes cambiarlo"
echo ""
echo "¿Cual es tu pgp de Keybase?"
read pgp
echo ""
echo "¿Qué quieres poner en detalles"
read details
echo ""
echo "¿Qué cantidad?"
read amount
echo ""
echo "¿Cual es la contraseña?"
read -s password
echo ""
echo "${password}" | $CLI tx staking create-validator --commission-max-change-rate=0.10 --commission-max-rate=1 --commission-rate=1 --moniker=${keyname} --min-self-delegation=1 --identity=${pgp} --from=${keyname} --details=${details} --chain-id=${chain_id} --pubkey=${pubkey} --amount=${amount}${UNIT}
