#!/bin/bash
#
# DANGER
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl) -> @cosmaut:matrix.org      #
#  @DerFredy       -> @derfredy:matrix.org     #
#                                              #
################################################
# DANGER use it carefully
PROJECT=kava
DAEMON=kvd
CLI=kvcli
UNIT=ukva

# service stop
kill -9 $(pgrep $DAEMON)
tmux kill-server

# backup data base
tar czf gaia-db.tgz ~/.$DAEMON/data
# check backup
if [[ $? != 0 ]] ; then
    exit $?
fi

# Download genesis
cd ~
wget https://github.com/$PROJECT/game-of-stakes/raw/master/genesis.json
cp ~/.$DAEMON/config/genesis.json ~/.$DAEMON/config/genesis.json.old
cp ~/genesis.json ~/.$DAEMON/config/genesis.json

# restet
~/bin/$DAEMON unsafe-reset-all
# restart
~/scripts/check-$DAEMON
