#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl) -> @cosmaut:matrix.org      #
#  @DerFredy -> @4llfr33d0m:matrix.org	       #
#  @Bitcoinera -> https://keybase.io/bitcoinera#
#                                              #
################################################

#Used variables
DAEMON=kvd
CLI=kvcli
UNIT=ukva

chain_id=`curl -s http://localhost:26657/status | jq -r '.result.node_info.network'`
keyname=`$CLI keys list | awk 'FNR==2{print $1}'`

#
# Read title 
#

echo "Write a title for your proposal:"
read title

#
# Read description 
#

echo "Write the description of your proposal:"
read description

#
# Read type
#
echo "What type is your proposal (text/software_upgrade/parameter_change)?:"
read type

#
# Read deposit
#
echo "What deposit would you like to use for your proposal?"
read deposit

#
# Read gas price
#
echo "What gas price you want to apply?"
read gasprice

#
# Read Wallet password
#

echo "Wallet password:"
read -s password

  echo "Submitting the proposal:"
  echo "$CLI tx gov submit-proposal --title "$title" --description "$description" --type $type --deposit=${deposit}$UNIT  --gas auto --gas-adjustment 1.5 --gas-prices ${gasprice}$UNIT --from=${keyname} --chain-id=$chain_id"
	$CLI tx gov submit-proposal --title $title --description $description --type $type --deposit=${deposit}$UNIT --gas auto --gas-adjustment 1.5 --gas-prices ${gasprice}$UNIT --from=${keyname} --chain-id=$chain_id

 
echo "done"
